version: "3"
services:
  db:
    image: mysql:5.7
    container_name: mysql-prod
    volumes:
      - prod_mysql:/var/lib/mysql
    networks:
      - prod_net_back
    environment:
      - MYSQL_ROOT_PASSWORD=MySql2019!
      - MYSQL_DATABASE=testedb
      - MYSQL_USER=luismatos
      - MYSQL_PASSWORD=teste123456

  backend:
    container_name: backend-prod
    image: back_prod:build_${BUILD_NUMBER}
    build:
      context: .
      args:
        - WAR_FILE=target/tasks-backend.war
        - CONTEXT=tasks-backend
    networks:
      - prod_net_back
      - prod_net_front
    #ports:
    #  - 9998:8080
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_USER=luismatos
      - DATABASE_PASSWD=teste123456
      #- DATABASE_UPDATE=none
    depends_on:
      - db

  frontend:
    container_name: frontend-prod
    image: front_prod:build_${BUILD_NUMBER}
    build:
        context: .
        args:
          - WAR_FILE=frontend/target/tasks.war
          - CONTEXT=tasks
    networks:
      - prod_net_front
    ports:
      - 9999:8080
    environment:
      - BACKEND_HOST=backend
      - BACKEND_PORT=8080
      - APP_VERSION=build_${BUILD_NUMBER}
    #depends_on:
    #  - backend

networks:
  prod_net_front:
  prod_net_back:
    driver: bridge

volumes:
  prod_mysql:
  prod_mysql_data: